export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const RECEIVED_CATEGORIES = 'RECEIVED_CATEGORIES';

export const GET_PRODUCT_FROM_CATEGORY = 'GET_PRODUCT_FROM_CATEGORY';
export const PRODUCTS_RECEIVED = 'PRODUCTS_RECEIVED';
